#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

FEED_URL="https://api.reseller.azarnuzy.com/api/catalog/feed.csv"

banner "Meta Commerce Catalog setup"

# ── Stage 1: create the catalog ────────────────────────────────────────────
stage "Commerce Manager: create the catalog"
say "WhatsApp is already connected (access token, phone number, verify token"
say "are all set). What's left is creating a product catalog and wiring it up."
open_url "https://business.facebook.com/commerce/catalogs"
step "Make sure you're in the same Business Portfolio as the connected WhatsApp Business Account (top-left picker)."
step "Click 'Add catalog' → choose 'E-commerce' → name it (e.g. 'Reseller App Catalog') → Create."
confirm "Catalog created?" || warn "come back to this stage once it exists"

# ── Stage 2: add the data feed ─────────────────────────────────────────────
stage "Add the product feed as a data source"
say "The API already serves a Meta-compatible CSV feed at:"
note "  $FEED_URL"
step "Opening it now so you can eyeball the CSV before pasting the URL into Meta."
open_url "$FEED_URL"
say "In the catalog you just created: Data Sources → Add Items → 'Data Feed' (Scheduled)."
step "Paste the feed URL above, set the schedule to Daily, and submit."
confirm "Feed source added?" || warn "come back to this stage once it's added"

# ── Stage 3: wait for the first import ─────────────────────────────────────
stage "Wait for the first feed import to finish"
say "Meta pulls the feed on submit for the first run. This can take a few minutes."
step "In the catalog's Data Sources tab, wait for the upload status to show 'Complete' (or check item errors if it fails)."
confirm "Feed processed with no errors?" || warn "check the item-level errors in Data Sources before continuing"

# ── Stage 4: connect the catalog to the WhatsApp Business Account ─────────
stage "Connect the catalog to the WhatsApp Business Account"
open_url "https://business.facebook.com/settings/whatsapp-business-accounts"
say "Meta's menu labels shift around; if this exact page doesn't show it, use the"
say "search box in Business Settings for 'Data Sources' → 'Catalogs'."
step "Select the connected WhatsApp Business Account → Data Sources → Catalogs → Connect a catalog."
step "Pick the catalog you created in Stage 1."
confirm "Catalog connected to the WhatsApp Business Account?" || warn "come back to this stage once connected"

# ── Stage 5: grant the messaging system user access to the catalog ────────
stage "Grant catalog access to the system user"
say "Without this, sending a catalog card via the API fails with a permission"
say "error even though the catalog looks connected in the UI."
open_url "https://business.facebook.com/settings/system-users"
step "Select the system user whose token is in META_WHATSAPP_ACCESS_TOKEN."
step "Assign Assets → Catalogs → select the catalog → grant 'Manage catalog' → Save."
confirm "Access granted?" || warn "come back to this stage if product cards fail to send later"

# ── Stage 6: capture the catalog ID ────────────────────────────────────────
stage "Copy the Catalog ID"
open_url "https://business.facebook.com/commerce/catalogs"
step "Open your catalog → Settings → copy the Catalog ID (a long numeric string)."
ask META_WHATSAPP_CATALOG_ID "Paste the Catalog ID:"
write_env META_WHATSAPP_CATALOG_ID "$META_WHATSAPP_CATALOG_ID"
note "Not sent to GitHub secrets: production reads this from env.production on the VPS, not CI."

# ── Stage 7: roll it out to production ─────────────────────────────────────
stage "Update production on the VPS"
warn "Requires deploy/compose.prod.yaml's META_WHATSAPP_CATALOG_ID passthrough to"
warn "already be live on main (this repo's fix must be merged and deployed first)."
say "This part is manual by design: this script never touches VPS credentials."
step "ssh tencent-lighthouse"
step "Edit /srv/apps/reseller-app/env.production and add (or update):"
note "    META_WHATSAPP_CATALOG_ID=$META_WHATSAPP_CATALOG_ID"
step "Then restart just the api service so it picks up the new value:"
note "    cd /srv/apps/reseller-app && docker compose --env-file env.production --env-file .release.env -f compose.prod.yaml up -d api"
confirm "Production env updated and api restarted?" || warn "finish this by hand before testing"

# ── Stage 8: verify end to end ──────────────────────────────────────────────
stage "Verify catalog cards actually send"
say "Message the business WhatsApp number with something that triggers a product"
say "search, recommendation, or best-seller reply."
step "Confirm a catalog card (not just plain text) comes back."
step "If it fails, check the API logs for a WhatsAppClientError:"
note "    docker compose --env-file env.production --env-file .release.env -f compose.prod.yaml logs --tail=100 api"
step "A permission-style failure here usually means Stage 5 (system user access) wasn't completed."
confirm "Catalog card confirmed working end to end?" || warn "revisit Stage 5 (permissions) or Stage 4 (connection) if it's still failing"

# ──────────────────────────────────────────────────────────────────────────

finish
